### ISSUE TITLE
Sign up and Login: Owner

### ISSUE THREAD

**Issue by rosefrancis-tech** [woof-board/woof#7]
Owner is a user who wants to use dog walking services.

As a user, when I visit the website, I am able to signup or log in from the first page.
As a user, when I sign up with the name, email and password, I need to fill in a form to continue using the service.
As a user, when I fill the registration form, it shows required fields (phone, address, dog details: name, breed, weight)
As a user, when I log in, I am able to view and edit my address and dog details from the dashboard
As a user, when I log in, I am able to book a dog walk from my dashboard

**Comment by nchow18** [comment]
still in progress, adding additional fields/page for the extra fields for OWNER signup
