### ISSUE TITLE
Sign up and Login: Walker

### ISSUE THREAD

**Issue by rosefrancis-tech** [woof-board/woof#8]
Walker is a user who offers dog walking services.

As a user, when I visit the website, I can go to the walker's signup/login page
As a user, when I sign up with the name, email and password, I need to fill in a form to continue using the service
As a user, when I fill the registration form, it shows required fields (phone, address, location of service)
As a user, when I log in, I am able to view and edit the phone, address, location of service from the dashboard
As a user, when I log in, I am able to update my availability for each day

**Comment by nchow18** [comment]
remaining: completed without HOOKS for QUERIES and MUTATIONS
